version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - ./logs:/var/log/pessoas
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki

  log-generator:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    container_name: log-generator
    volumes:
      - ./logs:/var/log/pessoas
    depends_on:
      - loki

  etl:
    build:
      context: ./scripts/etl
      dockerfile: Dockerfile
    container_name: etl-transformer
    volumes:
      - ./logs:/var/log/pessoas
    depends_on:
      - log-generator
